### PR TITLE
Updating dependencies and improving code

### PR DESCRIPTION
**Pull request by zoxon**
Deleted unnecessary build to dist folder
Added support for  `*.ts`, `*.tsx`, `*.jsx`
Update tests
Disable server compression in dev mode
Added ability to copy `className` from document `html` and `body`

### CODE REVIEW

**Comment by vixalien** [comment]
hey @zoxon.

this is a very interesting PR but it would be better to describe what you mean by "improving code". I'll review it anyways though.

thanks.

**Review by vixalien — CHANGES_REQUESTED** [review]
- in `package.json` why are you removing the building script and using the non-built versions of explosiv. remember that explosiv must be served to npm hence the published package must be as small as possible.
- why are you copying over the root document's class name?

**Comment by zoxon** [comment]
Build not needed anymore we in 2021. LTS Nodejs verson is 16 and it supports ESM imports.
I'm using [own library](https://github.com/zoxon/lit-htm) with gulp to doing the same, and it used ESM (that works fine)
I copy classNames from body and html becasue we don't have any another way to set this classnames (for tailwind for example)

**Review by vixalien — CHANGES_REQUESTED** [review]
I can approve copying over the document classnames

But I'm sorry I can't allow the building process to be removed. ESM support came in NodeJS 14 and many people aren't up to date yet. Plus, I don't want compatibility issues and I is important to consider that the build size is removed as the Explosiv package doesn't make assumptions on where it will be run (Node or browser or Deno or whatever)

**Comment by zoxon** [comment]
I don't use esm imports in this PR, only require. This mean it will be work like before. Nodejs can resolve common js modules.  
I can return back build, if you want but it's not needed and bundle will be bigger than source
Screenshot 2021-12-03 at 08 58 31

**Comment by zoxon** [comment]
I'm return back build script

**Review by vixalien — APPROVED** [review]
okay

**Pull request merged**
